#INCLUDE "rwmake.ch"
#INCLUDE "topconn.ch"

//------------------------------------------------------------------------------
/*{Protheus.doc} ADV020
Rotina para montagem da tela de amarracao tipo de chamado X atendente

@author 	Rogerio Onishi Candisani
@version 	P12
@since   	
*/
//------------------------------------------------------------------------------
User Function ADV020()

AxCadastro("ZZE","Tipo Chamado X Atendente")

Return