#INCLUDE "rwmake.ch"
#INCLUDE "topconn.ch"

//------------------------------------------------------------------------------
/*{Protheus.doc} ADV021
Rotina para montagem da tela de amarracao atendente X nivel de atendimento

@author 	Rogerio Onishi Candisani
@version 	P12
@since   	
*/
//------------------------------------------------------------------------------
User Function ADV021()

AxCadastro("ZZF","Atendente X Nivel de atendimento")

Return